/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kywoiyxslihcinrlwecm"
export const publicAnonKey = "sb_publishable_PZayjJAd6jKrPi-i0LoZOQ_EUPxAO0R"

// Base URL for the backend Edge Function
// Note: /server/ is the function name, routes are defined without the /make-server-467d3bfa prefix
export const serverBaseUrl = `https://${projectId}.supabase.co/functions/v1/server`